version: "3"

# Use different Dockerfiles and bind the working directories
# as volumes for local development. Override the production compose file with:
# ```docker-compose -f docker-compose.yml -f dev.docker-compose.yml up```
services:
  api:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./api:/api:ro

  web:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/web:ro
      - ./web/.next:/web/.next:rw
