version: "3"

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data/pg.sock:/var/run/postgres/postgres.sock

  api:
    build:
      context: ./api
    env_file:
      - .env
    volumes:
      - ./config.json:/config.json:ro
      - ./data/storage:/storage:rw
    depends_on:
      - "db"

  web:
    build:
      context: ./web
    depends_on:
      - "api"

  proxy:
    image: nginx:mainline
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/storage:/storage:ro
    command: >-
      /bin/sh -c '
      while :; do sleep 8h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"
      '
    depends_on:
      - "api"
      - "web"
