import sys
from db import Database

db = Database('postgresql+psycopg2://albumator:asdf@127.0.0.1:5432/albumator')
print(f"Added users {db.insert_users(['chumpy', 'skeletor', 'nacho', 'jojo'])}")
db.update_user_name(102, 'cheese')
print(f"All users: {[user.user_name for user in db.select_all_users()]}")
print(f"Added albums {db.insert_albums(['Landscape photos', 'Portraits'], 100)}")
print(f"Added photo {db.insert_photo('Mt Akina', 100, 200, '/path/to/preview1.jpg', '/path/to/some/file.raw')}")
print(f"Added edit {db.insert_edit('Mt Akina remix', 100, 300, '/path/to/preview2.jpg', '/path/to/some/file.xml')}")
print(f"A user's albums: {[album.album_name for album in db.select_user_albums(100)]}")
print(f"A user's photos: {[photo.photo_name for photo in db.select_user_photos(100)]}")
print(f"A photo's edits: {[edit.edit_name for edit in db.select_photo_edits(300)]}")

# db.select_all_users()
# db.select_user(user_id)
# db.select_users_by_name(user_name_list)
# db.insert_users(user_name_list)
# db.update_user_name(user_id, user_name)
# db.delete_users(user_id_list)
# db.select_album(album_id)
# db.select_user_albums(user_id)
# db.insert_albums(album_name_list, user_id)
# db.update_album_name(album_id, album_name)
# db.update_album_user_id(album_id, user_id)
# db.delete_albums(album_id_list)
# db.select_photo(photo_id)
# db.select_user_photos(user_id)
# db.select_album_photos(album_id)
# db.insert_photo(photo_name, user_id, album_id, file_preview, file_source)
# db.update_photo_name(photo_id, photo_name)
# db.update_photo_user_id(photo_id, user_id)
# db.update_photo_album_id(photo_id, album_id)
# db.update_photo_files(photo_id, file_preview, file_source)
# db.select_edit(edit_id)
# db.select_user_edits(user_id)
# db.select_photo_edits(photo_id)
# db.insert_edit(edit_name, user_id, photo_id, file_preview, file_source)
# db.update_edit_edit_name(edit_id, edit_name)
# db.update_edit_user_id(edit_id, user_id)
# db.update_edit_files(edit_id, file_preview, file_source)

if __name__ == '__main__':
  sys.exit(0)
