query Focal {
  accounts {
    role: accountRole
    name: accountName
    safename: accountSafename
    email: accountEmail
    createdAt
    editedAt
    previewFile {
      path: filePath
    }
    following {
      name: accountName
    }
    followers {
      name: accountName
    }
    blocked {
      name: accountName
    }
    blockedBy {
      name: accountName
    }
    bans {
      id: banId
      createdAt
      expiresAt
      name: banName
      text: banText
    }
    flags {
      id: flagId
      name: flagName
      text: flagText
    }
    notifications {
      id: notificationId
      createdAt
      viewedAt
      event {
        type: eventType
        account {
          name: accountName
        }
        photo {
          id: photoId
          title: photoTitle
        }
        edit {
          id: editId
          title: editTitle
        }
        reply {
          id: replyId
          text: replyText
        }
      }
    }
    photos {
      id: photoId
      title: photoTitle
      text: photoText
      createdAt
      editedAt
      previewFile {
        path: filePath
        width: imageWidth
        height: imageHeight
      }
      rawFile {
        path: filePath
        name: fileName
        ext: fileExtension
        size: fileSize
      }
      edits {
        id: editId
        title: editTitle
        createdAt
        account {
          name: accountName
        }
        previewFile {
          path: filePath
          width: imageWidth
          height: imageHeight
        }
      }
      replies {
        id: replyId
        text: replyText
        createdAt
        account {
          name: accountName
        }
      }
    }
    edits {
      id: editId
      title: editTitle
      text: editText
      createdAt
      editedAt
      previewFile {
        path: filePath
        width: imageWidth
        height: imageHeight
      }
      sidecarFile {
        path: filePath
        name: fileName
        ext: fileExtension
        size: fileSize
      }
      photo {
        id: photoId
        title: photoTitle
        createdAt
        account {
          name: accountName
        }
        previewFile {
          path: filePath
          width: imageWidth
          height: imageHeight
        }
      }
      replies {
        id: replyId
        text: replyText
        createdAt
        account {
          name: accountName
        }
      }
    }
    replies {
      id: replyId
      text: replyText
      createdAt
      editedAt
      photo {
        photoId
        photoTitle
        account {
          name: accountName
        }
      }
      edit {
        editId
        editTitle
        account {
          name: accountName
        }
      }
    }
  }
  events {
    eventId
    eventType
    createdAt
    account {
      name: accountName
    }
    photo {
      id: photoId
      title: photoTitle
      previewFile {
        path: filePath
        width: imageWidth
        height: imageHeight
      }
      reactions {
        reactionId
        reactionName
        reactionEmoji
      }
    }
    edit {
      id: editId
      title: editTitle
      previewFile {
        path: filePath
        width: imageWidth
        height: imageHeight
      }
      replies {
        replyId
        replyText
        account {
          name: accountName
        }
      }
    }
    reply {
      id: replyId
      text: replyText
      photo {
        id: photoId
        title: photoTitle
        previewFile {
          path: filePath
          width: imageWidth
          height: imageHeight
        }
        account {
          name: accountName
        }
      }
      edit {
        id: editId
        title: editTitle
        previewFile {
          path: filePath
          width: imageWidth
          height: imageHeight
        }
        account {
          name: accountName
        }
      }
    }
  }
  flags {
    id: flagId
    name: flagName
    text: flagText
  }
  bans {
    name: banName
    text: banText
    accounts {
      name: accountName
    }
  }
  reactions {
    name: reactionName
    emoji: reactionEmoji
    photos {
      photoId
      photoTitle
    }
    edits {
      editId
      editTitle
    }
    replies {
      replyId
      photo {
        id: photoId
      }
      edit {
        id: editId
      }
    }
  }
}
